### ISSUE TITLE
Send reason for status upstream

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetmon#1]
See https://github.com/Automattic/jetpack/issues/2796

Need to add a new call back to https://github.com/Automattic/jetmon/blob/1369d8cdec8a07e37dd9f786b69abcc6bb341aee/lib/wpcom.js#L10

that would be recorded here-ish: https://github.com/Automattic/jetmon/blob/c8c5c58f70027199d2d88f431c45a88b7a00ed8d/lib/httpcheck.js#L73

Could send back the HTTP status code and either "timeout" or a custom code. On the WP.com side, we can process that to an user-facing message.

**Comment by darthhexx** [comment]
This has been addressed in the last 3 PRs: #2, #3, and #4.
